# Copyright 2022 Google LLC
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

name: Check repo status
on:
  push:
    branches-ignore:
      - main
  pull_request:
jobs:
  watchers:
    name: All file watchers are enabled
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Check for disabled file watchers
        run: grep -q 'isEnabled="false"' .idea/watcherTasks.xml
  copyright:
    name: All files added by Sean contain a copyright header
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Check for copyright headers
        run: ./copyright-check.sh
  devsh:
    name: Changes from dev.sh are not committed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Check for commented "dev.sh remove" lines
        run: ! grep -qE '^#.*# dev.sh remove$' admin/.htaccess
      - name: Check for uncommented "dev.sh add" lines
        run: ! grep -qE '^[^#].*# dev.sh add' admin/.htaccess
