# Deploy GCP services on push
name: Deploy GCP services (test)
on:
  push:
    branches:
      - test
    paths:
      - 'gcp/**'
      - '.github/workflows/deploy-gcp-test.yml'
  workflow_dispatch:
jobs:
  resize-image:
    name: 'GCP: Deploy resize-image-test'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout test
        uses: actions/checkout@main
        with:
          ref: test
          fetch-depth: 2
      - name: Test changed files
        id: changed-files
        uses: tj-actions/changed-files@v15
        with:
          files: |
            gcp/resize-image/**
            .github/workflows/deploy-gcp-test.yml
      - name: Authenticate to Google Cloud
        if: steps.changed-files.outputs.any_changed == 'true' || github.event.action == 'workflow_dispatch'
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.GCP_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: Setup Cloud SDK
        if: steps.changed-files.outputs.any_changed == 'true' || github.event.action == 'workflow_dispatch'
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
      - name: Authorize Docker push
        if: steps.changed-files.outputs.any_changed == 'true' || github.event.action == 'workflow_dispatch'
        run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev
      - name: Enable Docker caching
        if: steps.changed-files.outputs.any_changed == 'true' || github.event.action == 'workflow_dispatch'
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Build container
        if: steps.changed-files.outputs.any_changed == 'true' || github.event.action == 'workflow_dispatch'
        run: docker build -t ${{ secrets.RESIZE_IMAGE_REPO }}/resize-image:test gcp/resize-image
      - name: Push to Artifact Registry
        if: steps.changed-files.outputs.any_changed == 'true' || github.event.action == 'workflow_dispatch'
        run: docker push ${{ secrets.RESIZE_IMAGE_REPO }}/resize-image:test
      - name: Deploy to Cloud Run
        if: steps.changed-files.outputs.any_changed == 'true' || github.event.action == 'workflow_dispatch'
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: resize-image-test
          image: ${{ secrets.RESIZE_IMAGE_REPO }}/resize-image:test
      - name: Clean up old versions
        if: steps.changed-files.outputs.any_changed == 'true' || github.event.action == 'workflow_dispatch'
        run: |
          gcloud artifacts docker images list ${{ secrets.RESIZE_IMAGE_REPO }}/resize-image --include-tags |
            awk '$3 ~ /^2/ { print $2 }' | 
            xargs -I % gcloud artifacts docker images delete ${{ secrets.RESIZE_IMAGE_REPO }}/resize-image@%
      - name: Get deployment URL
        if: steps.changed-files.outputs.any_changed == 'true' || github.event.action == 'workflow_dispatch'
        run: echo ${{ steps.deploy.outputs.url }}
  image-size:
    name: 'GCP: Deploy image-size-test'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout test
        uses: actions/checkout@main
        with:
          ref: test
          fetch-depth: 2
      - name: Test changed files
        id: changed-files
        uses: tj-actions/changed-files@v15
        with:
          files: |
            gcp/image-size/**
            .github/workflows/deploy-gcp-test.yml
      - name: Authenticate to Google Cloud
        if: steps.changed-files.outputs.any_changed == 'true' || github.event.action == 'workflow_dispatch'
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.GCP_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: Setup Cloud SDK
        if: steps.changed-files.outputs.any_changed == 'true' || github.event.action == 'workflow_dispatch'
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
      - name: Authorize Docker push
        if: steps.changed-files.outputs.any_changed == 'true' || github.event.action == 'workflow_dispatch'
        run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev
      - name: Enable Docker caching
        if: steps.changed-files.outputs.any_changed == 'true' || github.event.action == 'workflow_dispatch'
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Build container
        if: steps.changed-files.outputs.any_changed == 'true' || github.event.action == 'workflow_dispatch'
        run: docker build -t ${{ secrets.IMAGE_SIZE_REPO }}/image-size:test gcp/image-size
      - name: Push to Artifact Registry
        if: steps.changed-files.outputs.any_changed == 'true' || github.event.action == 'workflow_dispatch'
        run: docker push ${{ secrets.IMAGE_SIZE_REPO }}/image-size:test
      - name: Deploy to Cloud Run
        if: steps.changed-files.outputs.any_changed == 'true' || github.event.action == 'workflow_dispatch'
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: image-size-test
          image: ${{ secrets.IMAGE_SIZE_REPO }}/image-size:test
      - name: Clean up old versions
        if: steps.changed-files.outputs.any_changed == 'true' || github.event.action == 'workflow_dispatch'
        run: |
          gcloud artifacts docker images list ${{ secrets.IMAGE_SIZE_REPO }}/image-size --include-tags |
            awk '$3 ~ /^2/ { print $2 }' | 
            xargs -I % gcloud artifacts docker images delete ${{ secrets.IMAGE_SIZE_REPO }}/image-size@%
      - name: Get deployment URL
        if: steps.changed-files.outputs.any_changed == 'true' || github.event.action == 'workflow_dispatch'
        run: echo ${{ steps.deploy.outputs.url }}
