# Copyright 2022 Google LLC
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Deploy test branch to fmnas.org on push
name: Deploy test site
on:
  push:
    branches:
      - test
jobs:
  setup:
    name: Set up repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout test
        uses: actions/checkout@main
        with:
          ref: test
      - name: Create local branch
        run: git checkout -b test_deployment
  deploy:
    name: Deploy test website
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dev dependencies
        run: npm install
      - name: Cache PHP dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('composer.lock') }}
      - name: Install PHP dependencies
        uses: php-actions/composer@v6
        with:
          args: --ignore-platform-reqs
      - name: Compile public site stylesheets
        run: npx sass --style=compressed public:public
      - name: Compile public site scripts
        run: npx tsc -p public
      - name: Build admin client
        run: npx vite build admin/client
      - name: Set config values
        run: |
          npx ts-node handleparse.ts secrets/config.php.hbs \
          --db_name="${{ secrets.TEST_DB_NAME }}" \
          --db_username="${{ secrets.DB_USERNAME }}" \
          --db_pass="${{ secrets.DB_PASS }}" \
          --db_host="${{ secrets.DB_HOST }}" \
          --smtp_host="${{ secrets.SMTP_HOST }}" \
          --smtp_auth="${{ secrets.SMTP_AUTH }}" \
          --smtp_security="${{ secrets.SMTP_SECURITY }}" \
          --smtp_port="${{ secrets.SMTP_PORT }}" \
          --smtp_username="${{ secrets.SMTP_USERNAME }}" \
          --smtp_password="${{ secrets.SMTP_PASSWORD }}" \
          --image_size_endpoint="${{ secrets.IMAGE_SIZE_TEST_ENDPOINT }}" \
          --resize_image_endpoint="${{ secrets.RESIZE_IMAGE_TEST_ENDPOINT }}" \
          --asm_db="${{ secrets.ASM_WEB_DB }}" \
          --asm_host="${{ secrets.ASM_WEB_HOST }}" \
          --asm_user="${{ secrets.ASM_WEB_USER }}" \
          --asm_pass="${{ secrets.ASM_WEB_PASS }}" \
          --print_pdf_endpoint="${{ secrets.PRINT_PDF_TEST_ENDPOINT }}" \
          --minify_html_endpoint="${{ secrets.MINIFY_HTML_TEST_ENDPOINT }}"
      - name: Unignore config.php for upload
        run: echo '!secrets/config.php' >> .gitignore
      - name: Unignore vendor directory for upload
        run: sed -i '/\/vendor\//d' .gitignore
      - name: Unignore compiled files for upload
        run: |
          sed -i -E "/\.(css|js)$/d" public/.gitignore
          rm admin/.gitignore
      - name: Restrict access to test site
        run: cat public/.htaccess-test >> public/.htaccess
      - name: Restrict access to admin site
        run: cat admin/.htaccess-test >> admin/.htaccess
      - name: Commit changes to local branch
        run: |
          git config user.email "admin+automation@forgetmenotshelter.org"
          git config user.name "FMNAS Automation"
          git add .
          git commit -am "Automated changes for deployment"
      - name: Wait for GCP deployment
        uses: lewagon/wait-on-check-action@master
        with:
          ref: test
          check-regexp: 'GCP:.*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: SFTP upload
        uses: SamKirkland/FTP-Deploy-Action@3.0.0
        with:
          ftp-server: sftp://${{ secrets.TEST_SFTP_HOST }}${{ secrets.TEST_SITE_ROOT }}/
          ftp-username: ${{ secrets.TEST_SFTP_USER }}
          ftp-password: ${{ secrets.TEST_SFTP_PASS }}
          git-ftp-args: --insecure
      - name: Delete generated.php and cached descriptions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_SFTP_HOST }}
          username: ${{ secrets.TEST_SFTP_USER }}
          password: ${{ secrets.TEST_SFTP_PASS }}
          script: rm ${{ secrets.TEST_SITE_ROOT }}/src/generated.php ${{ secrets.TEST_SITE_ROOT }}/public/assets/cache/*.html || echo "Error $?"
      - name: Regenerate generated.php
        run: curl -u ${{ secrets.HTTP_CREDENTIALS }} ${{ secrets.TEST_SITE_URL }}
