# Deploy main branch to forgetmenotshelter.org on push
name: Deploy prod site
on:
  push:
    branches:
      - main
jobs:
  upload:
    name: Deploy prod website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@main
        with:
          ref: main
      - name: Create local branch
        run: git checkout -b prod_deployment
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install dev dependencies
        run: npm install
      - name: Cache PHP dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('composer.lock') }}
      - name: Install PHP dependencies
        uses: php-actions/composer@v6
        with:
          args: --ignore-platform-reqs
      - name: Compile public site stylesheets
        run: npx sass --style=compressed public:public
      - name: Compile public site scripts
        run: npx tsc -p public
      - name: Build admin client
        run: npx vite build admin/client
      - name: Set config values
        run: |
          npx ts-node handleparse.ts secrets/config.php.hbs \
          --db_name="${{ secrets.PROD_DB_NAME }}" \
          --db_username="${{ secrets.DB_USERNAME }}" \
          --db_pass="${{ secrets.DB_PASS }}" \
          --db_host="${{ secrets.DB_HOST }}" \
          --smtp_host="${{ secrets.SMTP_HOST }}" \
          --smtp_auth="${{ secrets.SMTP_AUTH }}" \
          --smtp_security="${{ secrets.SMTP_SECURITY }}" \
          --smtp_port="${{ secrets.SMTP_PORT }}" \
          --smtp_username="${{ secrets.SMTP_USERNAME }}" \
          --smtp_password="${{ secrets.SMTP_PASSWORD }}" \
          --image_size_endpoint="${{ secrets.IMAGE_SIZE_PROD_ENDPOINT }}" \
          --resize_image_endpoint="${{ secrets.RESIZE_IMAGE_PROD_ENDPOINT }}"
      - name: Require HTTPS to access public site
        run: cat public/.htaccess-prod >> public/.htaccess
      - name: Restrict access to admin site
        run: cat admin/.htaccess-prod >> admin/.htaccess
      - name: Disable error reporting on prod site
        run: echo '<?php' > src/common-test.php
      - name: Unignore config.php for upload
        run: echo '!secrets/config.php' >> .gitignore
      - name: Unignore vendor directory for upload
        run: sed -i '/\/vendor\//d' .gitignore
      - name: Unignore compiled files for upload
        run: |
          sed -i -E "/\.(css|js)$/d" public/.gitignore
          rm admin/.gitignore
      - name: Remove tester.php
        run: rm public/tester.php
      - name: Commit changes to local branch
        run: |
          git config user.email "admin+automation@forgetmenotshelter.org"
          git config user.name "FMNAS Automation"
          git add .
          git commit -am "Automated changes for deployment"
      - name: Wait for GCP deployment
        uses: lewagon/wait-on-check-action@master
        with:
          ref: prod
          check-regexp: 'GCP:.*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: SFTP upload
        uses: SamKirkland/FTP-Deploy-Action@3.0.0
        with:
          ftp-server: sftp://${{ secrets.PROD_SFTP_HOST }}${{ secrets.PROD_SITE_ROOT }}/
          ftp-username: ${{ secrets.PROD_SFTP_USER }}
          ftp-password: ${{ secrets.PROD_SFTP_PASS }}
          git-ftp-args: --insecure
      - name: Delete generated.php and cached descriptions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SFTP_HOST }}
          username: ${{ secrets.PROD_SFTP_USER }}
          password: ${{ secrets.PROD_SFTP_PASS }}
          script: rm ${{ secrets.PROD_SITE_ROOT }}/src/generated.php ${{ secrets.PROD_SITE_ROOT }}/public/assets/cache/*.html || echo "Error $?"
      - name: Regenerate generated.php
        run: curl ${{ secrets.PROD_SITE_URL }}
