# Deploy test branch to fmnas.org on push
name: Deploy test site
on:
  push:
    branches:
      - test
jobs:
  upload:
    name: Upload website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout test
        uses: actions/checkout@main
        with:
          ref: test
      - name: Create local branch
        run: git checkout -b test_deployment
      - name: Restrict access to test site
        run: cat public/.htaccess-test >> public/.htaccess
      - name: Restrict access to test admin site
        run: cat admin/.htaccess-test >> admin/.htaccess
      - name: Commit changes to local branch
        run: |
          git config user.email "admin+automation@forgetmenotshelter.org"
          git config user.name "FMNAS Automation"
          git add .
          git commit -am "Automated changes for deployment"
      - name: SFTP upload
        uses: SamKirkland/FTP-Deploy-Action@3.0.0
        with:
          ftp-server: sftp://${{ secrets.TEST_SFTP_HOST }}${{ secrets.TEST_SITE_ROOT }}/
          ftp-username: ${{ secrets.TEST_SFTP_USER }}
          ftp-password: ${{ secrets.TEST_SFTP_PASS }}
          git-ftp-args: --insecure
