# Copyright 2022 Google LLC
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

name: Image size benchmark regression test
on:
  push:
    branches-ignore:
      - main
    paths:
      - .github/workflows/image-size-regression-test.yml
      - gcp/image-size/**
      - tests/blackbox/bin/results.dart
      - tests/blackbox/bin/service.dart
      - tests/blackbox/bin/image_size.dart
      - tests/blackbox/test/regression_test_helper.dart
      - tests/blackbox/test/image_size_regression_test.dart
      - tests/blackbox/goldens/image_size_regression_test.json
  pull_request:
    branches-ignore:
      - main
    paths:
      - .github/workflows/image-size-regression-test.yml
      - gcp/image-size/**
      - tests/blackbox/bin/results.dart
      - tests/blackbox/bin/service.dart
      - tests/blackbox/bin/image_size.dart
      - tests/blackbox/test/regression_test_helper.dart
      - tests/blackbox/test/image_size_regression_test.dart
      - tests/blackbox/goldens/image_size_regression_test.json
  workflow_dispatch:
jobs:
  test:
    name: Run image_size_regression_test
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@main
      - run: docker-compose pull image-size.fmnas
      - name: Enable Docker layer caching
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: fmnas-{hash}
          restore-keys: |
            fmnas-
      - run: docker-compose build image-size.fmnas
      - run: docker-compose run -d --name image-size -p 8080 image-size.fmnas
      - name: Find the ephemeral port
        run: docker-compose ps | perl -lane '/image-size.+0:(\d+)->8080\/tcp/ && print "PORT=$1"' | tee -a $GITHUB_ENV
      - uses: dart-lang/setup-dart@v1
      - name: Build blackbox
        run: |
          cd tests/blackbox
          dart pub get
          dart run build_runner build
      - name: Wait for service
        run: |
          sudo apt install -y wait-for-it
          wait-for-it -h localhost -p ${{ env.PORT }} -t 300
      - name: Run image_size_regression_test
        run: |
          cd tests/blackbox
          ENVIRONMENT_KEY="ubuntu-latest" \
          IMAGE_SIZE_ENDPOINT="http://localhost:${{ env.PORT }}" \
          dart test test/image_size_regression_test.dart
      - name: Create pull request to update golden values
        if: steps.changed.outputs.changed == '1'
        uses: peter-evans/create-pull-request@v3
        with:
          committer: "FMNAS Automation <admin+automation@forgetmenotshelter.org>"
          author: "FMNAS Automation <admin+automation@forgetmenotshelter.org>"
          branch: image-size-benchmark/${{ github.ref_name }}
          delete-branch: true
          commit-message: Update reference values for image_size_regression_test.
      - name: Bring down service
        if: always()
        run: docker-compose down
