# Copyright 2022 Google LLC
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

name: Merge main into test
on:
  push:
    branches:
      - main
jobs:
  merge:
    name: Merge main into test
    runs-on: ubuntu-latest
    steps:
      - name: Wait for todo-issues
        uses: lewagon/wait-on-check-action@master
        with:
          ref: test
          check-name: 'Sync TODOs'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success,skipped,cancelled,failure
      - name: Merge main into test
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: test
          github_token: ${{ secrets.GITHUB_TOKEN }}
