# Depends on MongoDB Atlas instance using apps account SSO.
name: Create issues from TODOs
on:
  push:
    branches:
      - test
      - main
jobs:
  todos:
    name: Sync TODOs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
        with:
          ref: 'test'
      - name: Run todo-actions
        uses: dtinth/todo-actions@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TODO_ACTIONS_MONGO_URL: ${{ secrets.TODO_ACTIONS_MONGO_URL }}
